val = int(input())
print(val)
val, rem = divmod(val, 100)
print("%d nota(s) de R$ 100,00" % val)
val, rem = divmod(rem, 50)
print("%d nota(s) de R$ 50,00" % val)
val, rem = divmod(rem, 20)
print("%d nota(s) de R$ 20,00" % val)
val, rem = divmod(rem, 10)
print("%d nota(s) de R$ 10,00" % val)
val, rem = divmod(rem, 5)
print("%d nota(s) de R$ 5,00" % val)
val, rem = divmod(rem, 2)
print("%d nota(s) de R$ 2,00" % val)
val, rem = divmod(rem, 1)
print("%d nota(s) de R$ 1,00" % val)
